CUDA_VISIBLE_DEVICES=0,1,2 python3 main_linear.py \
    --dataset imagenet \
    --backbone resnet18 \
    --data_dir /projects/imagesets \
    --train_dir  imagenet/RawImages/train \
    --val_dir  imagenet/RawImages/val \
    --max_epochs 100 \
    --devices 0,1,2 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --scheduler step \
    --lr 3.0 \
    --lr_decay_steps 60 80 \
    --weight_decay 0 \
    --batch_size 512 \
    --num_workers 5 \
    --pretrained_feature_extractor /projects/biofid/augmentations/solo-learn/trained_models/mocov2plus/3dfbkqd7/imagenet_original-3dfbkqd7-ep=99.ckpt \
    --name linear_eval_moco \
    --project imagenet_results \
    --entity labrats \
    --wandb \
    --dali
