cifar_transform_dict = {
                0:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                1:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                2:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                3:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                4:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                5:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                6:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                7:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                8:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                9:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                10:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                11:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                12:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                13:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                14:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                15:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                16:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                17:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                18:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
                19:CifarTransform(cifar="cifar100",brightness=0.4,contrast=0.4,
                                saturation=0.2,
                                hue=0.1,
                                color_jitter_prob = 0.8,
                                min_scale = 0.08),
            }